.gitignore, README.md, aws/src/lambdas/package.json, extension/src/hashpass/package.json, package.json
No issue was assigned for this.
This is to setup the file structure for the repository.
No behavior expeted.
=> Added basic file structure for Repo

extension/src/hashpass/test.txt
=> Test commit

package.json, tsconfig.json
=> Added tsconfig.json

.github/workflows/build-app.yml, extension/src/hashpass/app/page.tsx
Issue: #16 
This PR is to setup the github action workflow that will automated build our project when a PR is created, edited, closed, or synchronized. 
The expected behavior is that GitHub actions will attempt to build our project upon creation or any change to a PR and its code.
=> 16 build application through continuous integration

.github/workflows/build-app.yml, extension/src/hashpass/package.json
Issue #20 
The script will now run tests and use different npm versions when the workflow is triggered after building
The building workflow should run the testing suite and use different versions of npm when building.
=> 20 update ci actions to run unit tests

extension/src/hashpass/app/api/hash/route.ts, extension/src/hashpass/app/hashing_test_component.tsx, extension/src/hashpass/app/page.tsx, extension/src/hashpass/package.json, extension/src/hashpass/tsconfig.json
#4 
This PR implements simple password hash generation using argon2 as a server side api
Enter any value in the input field and click on "Hash" and an argon2 hash value will be produced.
=> Added argon2 hashing

.github/workflows/build-app.yml, eslint.config.mjs, extension/src/hashpass/build-log.js, extension/src/hashpass/package.json, extension/src/hashpass/public/service-worker.js, package.json
#31 
Adding a linter to the GitHub actions as our software QA in our Continuous Integration.
The Linter should point out any issues and fail the checks needed for a pull request.
=> Add ESLint GitHub Action

extension/src/hashpass/public/content.js
#30 
Expanded detection for sign-in fields. Added a filter to better optimize popups for only inputs in sign in forms rather than promotional and other inputs.
Pop up appears only with sign in fields and not other fields (e.g promotional entrance of email).
No additional notes are provided.
=> 30 update content scripts to ensure login is found

extension/src/hashpass/app/popup/page.tsx, extension/src/hashpass/app/security_components/enc_dec_tool.tsx, extension/src/hashpass/package.json
#38 
This ticket creates basic AES encryption and decryption abilities.
If a user id and a simple password (encryption key) is entered, then an encrypted version of the plain text is displayed.
This ticket is a proof of concept and will be refactored as a tool in a future ticket.
=> Created basic AES tool on extension side

extension/src/hashpass/app/dashboard/page.tsx, extension/src/hashpass/app/login/page.tsx, extension/src/hashpass/app/popup/page.tsx, extension/src/hashpass/public/service-worker.js
#41 
Attempted to implement navigation from the extension to a new chrome tab to login. While the attempt to navigate to a new tab failed, navigating within pages in the extension worked.
Should be able to navigate from the popup to the login within the extension.
Still need to figure out how to open up tabs from the extension!
=> Added functionilty to move pages within extension

extension/src/hashpass/app/hashpass_signup/page.tsx, extension/src/hashpass/package.json
#49 
Created sign up page with name, email, phone number, security questions, and simple passphrase.
A form should be completed by user with their information.
=> 49 create sign up page

extension/src/hashpass/app/popup/page.tsx, extension/src/hashpass/app/site_login_popup/page.tsx, extension/src/hashpass/app/site_login_popup/site_login_component.tsx, extension/src/hashpass/app/site_signup_popup/page.tsx, extension/src/hashpass/app/site_signup_popup/site_signup_component.tsx, extension/src/hashpass/app/site_signup_signin_popup/page.tsx, extension/src/hashpass/public/content.js, extension/src/hashpass/public/service-worker.js
=> 51 create logic to detect if a sign up or a sign in is required for a certain website

extension/src/hashpass/app/popup/page.tsx, extension/src/hashpass/app/site_login_popup/site_login_component.tsx, extension/src/hashpass/app/site_signup_popup/site_signup_component.tsx, extension/src/hashpass/public/content.js, extension/src/hashpass/public/service-worker.js
#55 
Previously the popup was a new browser window which would not have let us access the previous tab. Now, we have a way to use extension popups to address that issue.
When you go to a log in site, an extension popup must be opened displaying log in logic. Same for Sign up.
=> Changed the popup from a new tab window to an extension popup window

extension/src/hashpass/app/api/user-signup/route.ts, extension/src/hashpass/app/hashpass_signup/page.tsx, extension/src/hashpass/app/utils/sshTunnel.ts, extension/src/hashpass/next.config.ts, extension/src/hashpass/package.json
#53 
Sends the data from the sign up page of user to the MySQL RDS via ssh tunneling.
Users should be able to enter in data from signup page and this data should be visible in the MySQL database.
=> 53 send signup form data to aws database

extension/src/hashpass/app/api/user-signup/route.ts, extension/src/hashpass/package.json
#60
This issue makes sure the data we are sending to the database is encrypted using AES, so that the data is secure if it is intercepted or the database is compromised.
Each of the fields in the sign up page is encrypted before the SQL query is run on the database. The data in the database should look encrypted from now on.
=> Data sent to users table encrypted

extension/src/hashpass/app/security_components/components/password_generator.tsx, extension/src/hashpass/app/test_page/page.tsx
#66 
Added password generator to test page
Password generator is added to the test page and should log the generated password to console
=> Made changes to Test page to demo password generation

extension/src/hashpass/app/api/user-signup/route.ts, extension/src/hashpass/app/hashpass_signup/page.tsx
#68 
Validate Information added to Sign up page, now have to store email unencrypted due to potential duplicates.
Email requires @, phone number requires only numbers, password need to be at least 8 characters, 1 number, and 1 special character.
=> 68 refine sign up page

extension/src/hashpass/app/hashpass_signup/page.tsx
#74 
Making user signup passphrase stronger to ensure attackers cannot crack it.
Affects user sign up to get stronger passphrase.
no additional notes.
=> Made passphrase requirements stronger on sign up

extension/src/hashpass/app/site_login_popup/site_login_component.tsx, extension/src/hashpass/public/dist/components.bundle.js, extension/src/hashpass/public/manifest.json, extension/src/hashpass/public/service-worker.js
#50 
Allows extension to automatically put information into login fields.
After clicking the button, the text should be entered into login field.
No additional notes.
=> entering info into login field

aws/src/lambdas/calcHash/index.js, extension/src/hashpass/app/security_components/components/password_generator.tsx, extension/src/hashpass/app/security_components/tools/AES_tool.tsx, extension/src/hashpass/app/site_login_popup/site_login_component.tsx, extension/src/hashpass/app/test_page/page.tsx, extension/src/hashpass/public/dist/components.bundle.js
#73 
Though this doesn't solve finduuid, it ensures finduuid can be appropriately called as security inconsistencies have been fixed.
If you make a postman call to the finduuid lambda with the key "testkey" the plaintext "testuuid2" will be returned.
Also, the vault authentication is completed but will be added in another PR.
=> 73 complete finduuid lambda function

aws/src/lambdas/getUserInfo/index.mjs, aws/src/lambdas/getUserInfo/package.json
#85 
API to return encrypted name, email, and encrypted phone number given a UUID.
Given a UUID through Postman, the API returns the corresponding encrypted name, email, and encrypted phone number.
Terraform for API still needs to be added.
=> added lambda function code

aws/src/lambdas/insertBlockedDomain/index.js, aws/src/lambdas/insertBlockedDomain/index.ts, aws/src/lambdas/insertBlockedDomain/package.json, extension/src/hashpass/app/site_login_popup/site_login_component.tsx, extension/src/hashpass/app/site_signup_popup/site_signup_component.tsx, extension/src/hashpass/public/dist/components.bundle.js
#117 
Adds button to add domain name to blocked websites table.
If a user enters their passphrase and clicks the block website button, it will get added to the database if it not there already.
No additional notes
=> 117 add button to block website
